Feat(contact-tagging): Add support tagable contacts with bulk action
beabee-communityrm/monorepo pull request #63
Opened 2024-10-29 15:36 UTC by JumpLink

2024-10-31 15:20 UTC, JumpLink commented
@wpf500 I initially based my implementation on  `CalloutTag` , but then deviated from it. In the `ContactTag` model, I now only store the tags and no reference to the contact (`CalloutTag` stores the `calloutId`). Instead, I have created a `contact_tag_assignments` table using `@ManyToMany("ContactTag", "contact")` and `@JoinTable({...})`, which is used for the assignments. For callout responses, tags are managed per callout; for contacts, they are managed globally. Maybe you would like to take a look at my unfinished implementation? Feel free to give me suggestions on what else could be combined.

2024-11-01 14:17 UTC, wpf500 reviewed
A few small comments but in general this is really great :tada:. Well on it's way to being one of those magical PRs that adds a feature with a negative line count :smile:

2024-11-01 14:17 UTC, wpf500 commented on apps/backend/src/api/controllers/ContactController.ts
> +  @Get("/tags")
I think it might be cleaner if these endpoints sit in a different controller under `/contact-tags` rather than `/contacts`. What do you think?

2024-11-01 14:17 UTC, wpf500 commented on apps/backend/src/api/transformers/ContactTransformer.ts
> +      if (query.with?.includes(GetContactWith.Tags)) {
This is another one of these "only knowledge in my head" moments.

This join can return more than one row, so it can't be done in the main query. The pagination logic assumes one row per contact, which wouldn't be the case if a contact had multiple tags. This would mean `OFFSET` no longer works as intended.

This is what `loadContactRoles` in `modifyItems` is all about. It loads all the relevant contact roles after the initial query. You need to fetch the contact tags in the same way.

2024-11-01 14:17 UTC, wpf500 commented on packages/core/src/models/Contact.ts
> +  @JoinTable({
I think it would be better to explicitly define this table as a model (like `CalloutResponseTag`)?

It's more explicit and also means we can save other data about the relationship. In particular, it would be good to have a `@CreateDateColumn() date: Date` column which stores when the tag was assigned (again, see `CalloutResponseTag` for reference)

2024-11-06 09:17 UTC, JumpLink commented on apps/backend/src/api/transformers/ContactTransformer.ts
> +      if (query.with?.includes(GetContactWith.Tags)) {
Did I now do it like in the CalloutResponseTransformer

2024-11-06 09:17 UTC, JumpLink commented on packages/core/src/models/Contact.ts
> +  @JoinTable({
implemented now

2024-11-06 09:20 UTC, JumpLink commented on apps/backend/src/api/controllers/ContactController.ts
> +  @Get("/tags")
Yes, I had considered that too.

2024-11-06 16:05 UTC, JumpLink commented on apps/backend/src/api/controllers/ContactController.ts
> +  @Get("/tags")
@wpf500 I've changed it now, but now it's no longer consistent with the callout tags, so maybe they should get their own controller too.

2024-11-11 09:29 UTC, wpf500 reviewed
This is looking amazing so far. Thanks for adding so much documentation, cleaning up the code, giving it a better structure... on top of implementing the tagging in such a way that we could easily add more taggable entities in the future.

2024-11-11 09:29 UTC, wpf500 commented on apps/backend/src/api/controllers/CalloutResponseController.ts
> +    @PartialBody() data: Partial<CreateCalloutResponseDto>
I think the type here has to be `CreateCalloutResponseDto` because generics break the reflection that `class-transformer` uses to create the class, which means this just becomes a generic object which doesn't get validated.

See:
https://github.com/typestack/class-transformer?tab=readme-ov-file#working-with-generics
https://stackoverflow.com/questions/57797381/validation-does-not-work-with-partialdto-nestjs

Really we should do what they suggest in those links, which is to have a helper which creates a concrete "partial" class that can be reflected against.

2024-11-11 09:29 UTC, wpf500 commented on apps/backend/src/api/controllers/ContactController.ts
> +    return await ContactTransformer.updateOneByContact(auth, target, data);
Thanks for cleaning this up :tada:

2024-11-11 09:29 UTC, wpf500 commented on apps/backend/src/api/controllers/ContactTagController.ts
> +      rules: {
I think you can just not declare `rules` here no?

```ts
{ limit: -1 }
```

2024-11-12 09:39 UTC, JumpLink commented on apps/backend/src/api/controllers/CalloutResponseController.ts
> +    @PartialBody() data: Partial<CreateCalloutResponseDto>
Implemented in this commit: https://github.com/beabee-communityrm/monorepo/pull/63/commits/1925031e425b81d0e1e093938d730f0378a929eb

2024-11-12 09:43 UTC, JumpLink commented on apps/backend/src/api/controllers/ContactTagController.ts
> +      rules: {
Yes, thank you

2024-11-12 09:57 UTC, JumpLink commented
> This is looking amazing so far. Thanks for adding so much documentation, cleaning up the code, giving it a better structure... on top of implementing the tagging in such a way that we could easily add more taggable entities in the future.

I was very happy to do so, I found it difficult to understand (and I still haven't fully understood it) but the tidying up and documenting helped me to do so, so it wasn't entirely self-serving ;)

2024-11-12 09:59 UTC, JumpLink commented on apps/backend/src/api/controllers/CalloutResponseController.ts
> +    @PartialBody() data: Partial<CreateCalloutResponseDto>
And https://github.com/beabee-communityrm/monorepo/pull/63/commits/7267ac5ef10fa3688e2f2a5b3661d1878ce17bea

2024-11-12 12:59 UTC, JumpLink commented on apps/backend/src/api/controllers/CalloutResponseController.ts
> +    @PartialBody() data: Partial<CreateCalloutResponseDto>
I have now undone that and simply created a new DTO class instead.

2024-11-13 16:50 UTC, wpf500 reviewed
A few minor comments, but generally looks really great :tada:

2024-11-13 16:50 UTC, wpf500 commented on apps/backend/src/api/dto/CalloutResponseDto.ts
> +  // TODO: validate
This is good for now, but at some point we should look into using some helpers like the NestJS ones to avoid all the boilerplate.

https://docs.nestjs.com/openapi/mapped-types

2024-11-13 16:50 UTC, wpf500 commented on apps/backend/src/api/transformers/ContactExporter.ts
> +import { Contact, ContactTagAssignment } from "@beabee/core/models";
Unused import can be removed

2024-11-13 16:50 UTC, wpf500 commented on apps/backend/src/tools/database/anonymisers/models.ts
> +  // TODO: Move to contactAnonymiser?
Is this TODO still relevant?

2024-11-13 16:50 UTC, wpf500 commented on apps/backend/src/tools/database/anonymisers/models.ts
> +    tagId: () => uuidv4()
Can you move this up as this file is generally (hopefully) in alphabetical order.

We need an anonymiser for the contact tag table too, otherwise the export/import will break as the `tagId` in this table won't be a valid foreign key

Something like
```ts
const contactTagAnonymiser = createModelAnonymiser(ContactTag, {
  id: () => uuidv4(),
  name: () => chance.word(),
  description: () => chance.sentence()
});

2024-11-13 16:50 UTC, wpf500 commented on apps/backend/src/api/transformers/BaseContactTransformer.ts
> +function tagField(): FilterHandler {
I think this can be deleted now?

2024-11-13 17:03 UTC, wpf500 commented
One other question: have you tested the migration against an instance that had old style tags to migrate? Did it work on dev for example?

2024-11-13 18:18 UTC, JumpLink commented on apps/backend/src/tools/database/anonymisers/models.ts
> +  // TODO: Move to contactAnonymiser?
This comes from your last change where you anonymised the old tags, I wasn't sure if I should do something similar, hadn't looked at it more closely, but actually the tags should only be output if this is specified with "with"

2024-11-13 18:21 UTC, JumpLink commented
> One other question: have you tested the migration against an instance that had old style tags to migrate? Did it work on dev for example?

Yes you can look at this on dev, the old tags have been successfully preserved

2024-11-14 08:12 UTC, JumpLink commented on apps/backend/src/api/transformers/BaseContactTransformer.ts
> +function tagField(): FilterHandler {
Yes, thank you

2024-11-14 08:22 UTC, JumpLink commented on apps/backend/src/tools/database/anonymisers/models.ts
> +    tagId: () => uuidv4()
I added it and included it in the exports in `src/tools/database/export.ts`. Do I need to do anything else?

2024-11-14 08:24 UTC, JumpLink commented on apps/backend/src/tools/database/anonymisers/models.ts
> +  // TODO: Move to contactAnonymiser?
I have now removed the property tags here.

2024-11-14 08:26 UTC, JumpLink commented on apps/backend/src/api/dto/CalloutResponseDto.ts
> +  // TODO: validate
This helper can be found here but requires other helpers to: https://github.com/nestjs/mapped-types/blob/master/lib/partial-type.helper.ts

2024-11-14 13:43 UTC, wpf500 requested changes

2024-11-14 13:43 UTC, wpf500 commented on packages/core/src/errors/DuplicateTagNameError.ts
> +    return (
You should use `isDuplicateError` here with the field name rather than the constraint ID.

In theory the constraint ID should be a cleaner way of checking this, but at the moment it's autogenerated by TypeORM and there's no guarantee it will stay the same.

2024-11-15 09:23 UTC, JumpLink commented
With my lastest changes I have implemented:
* Ordered tags
* Wrap/break tags for items with many tags
* Improved delete tag translation
* Better error message on duplicate tag names
* Readd callout filter group for contacts
* Do not disable the toggle button if no item is selected to be able to reach the tag manager without a selection
* Keep the selection to be able to toggle multiple tags for the same selected items
* Fixed Tag Manager route from detail pages
* Make tags clickable

2024-11-15 09:31 UTC, merged